### ISSUE TITLE
指令建议

### ISSUE THREAD

**Issue by henlowornd** [NriotHrreion/Craftmine-App#6]
/setspawn 设置玩家角色所在地为出生点
/tpa xxx 传送至某位玩家（仅联机可用）
/kill 重置玩家位置

**Comment by NriotHrreion** [comment]
之后会慢慢加进去的👌

**Comment by NriotHrreion** [comment]
已将`/kill`指令改为`/suicide`并加入游戏，`/kill`指令将在多人游戏中实现
