### ISSUE TITLE
杂项

### ISSUE THREAD

**Issue by henlowornd** [NriotHrreion/Craftmine-App#7]
当前版本玩家的下落速度实在太慢了。。。走楼梯像三更半夜喝的断片的老赌棍一样

**Comment by henlowornd** [comment]
![image](https://user-images.githubusercontent.com/82158403/125757171-a46202b9-813a-4abb-a432-050e243b34f9.png)
bug or  not

**Comment by NriotHrreion** [comment]
请分开反馈
